# Generated by Django 5.2.7 on 2025-10-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('study_year', models.IntegerField()),
                ('enrollment_date', models.DateField()),
                ('courses', models.ManyToManyField(to='course.course')),
            ],
        ),
    ]
